services:
  mongo_db:
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db

  api:
    build: .
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      MONGO_DB_URI: mongodb://mongo_db:27017
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
